[project]
name = "dtw-benchmark"
version = "0.1.0"
description = "Benchmark DTW implementations"
readme = "README.md"
requires-python = ">=3.13"
authors = [
  { name = "Maxime Poli" },
  { name = "CoML", email = "dev@cognitive-ml.fr" }
]
dependencies = [
  "numba>=0.62.1",
  "numpy>=2.3.4",
  "packaging>=26.2",
  "torch>=2.9.0",
  "torchdtw",
]

[build-system]
requires = [
  "cython>=3.1.6",
  "numpy>=2.3.4",
  "setuptools>=83.0.0",
]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
torchdtw = { workspace = true }
