exclude = "uv.lock"

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.24.1"
hooks = [{ id = "zizmor" }]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.45.1"
hooks = [{ id = "typos" }]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v0.9.17"
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint" },
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-clang-format"
rev = "v22.1.3"
hooks = [{ id = "clang-format" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.10"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.29"
hooks = [
  { id = "uv-lock" },
  { id = "uv-audit" },
]
