[project]
name = "torchdtw"
description = "PyTorch DTW C++ extension"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "Maxime Poli" },
  { name = "CoML", email = "dev@cognitive-ml.fr" },
]
keywords = ["machine learning"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: C++",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
  "torch>=2.10.0",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
  "dtw-python>=1.7",
  "hypothesis>=6.142.5",
  "pytest>=8.4.2",
]

[build-system]
requires = [
  "ninja>=1.11",
  "numpy>=1.26.4",
  "setuptools>=80.9.0",
  "setuptools-scm>=9.2.2",
  "torch>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",  # missing-trailing-comma
  "D107",  # undocumented-public-init
  "D203",  # incorrect-blank-line-before-class
  "D213",  # multi-line-summary-second-line
  "N803",  # invalid-argument-name
  "N806",  # non-lowercase-variable-in-function
  "PLR0913",  # too-many-arguments
]

[tool.ruff.lint.pylint]
allow-magic-value-types = ["int", "str"]

[tool.ruff.lint.flake8-self]
ignore-names = ["_check"]

[tool.ruff.lint.pep8-naming]
ignore-names = ["F"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { file = "setup.py" },
  { file = "src/torchdtw/csrc/dtw.cpp" },
  { file = "src/torchdtw/csrc/cuda/dtw.cu" },
  { file = "benchmark/src/dtw_benchmark/dtw_cython.pyx" },
]

[tool.uv.workspace]
members = [
  "benchmark",
  "torchdtw",
]
